import { useEffect, useState } from 'react';
import apiClient from '../../api/client';
import { Video, Calendar, Clock, User, ExternalLink } from 'lucide-react';

export default function TPOInterviews() {
  const [interviews, setInterviews] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function loadInterviews() {
      try {
        const res = await apiClient.get('/interviews');
        setInterviews(res.data || []);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    }
    loadInterviews();
  }, []);

  return (
    <div style={{ maxWidth: '1100px', margin: '0 auto', display: 'flex', flexDirection: 'column', gap: '2rem' }}>
      <div>
        <h2 className="text-gradient">Master Campus Interview Schedule</h2>
        <p style={{ margin: 0 }}>Oversight across all ongoing and scheduled technical rounds, panels, and meeting links.</p>
      </div>

      {loading ? (
        <div style={{ padding: '3rem', textAlign: 'center' }}>Loading campus interview schedules...</div>
      ) : interviews.length === 0 ? (
        <div className="glass-panel" style={{ padding: '3.5rem 2rem', textAlign: 'center' }}>
          <Video size={48} style={{ margin: '0 auto 1rem', color: 'var(--text-secondary)' }} />
          <h3>No Campus Interviews Scheduled Today</h3>
          <p style={{ color: 'var(--text-secondary)' }}>Interview slots generated by recruiters will appear here in real-time.</p>
        </div>
      ) : (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))', gap: '1.25rem' }}>
          {interviews.map((iv) => (
            <div key={iv.id} className="glass-panel" style={{ padding: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                <div>
                  <h4 style={{ margin: 0, fontSize: '1.1rem' }}>{iv.round_name}</h4>
                  <div style={{ fontSize: '0.8rem', color: 'var(--primary)', fontWeight: 600 }}>{iv.company_name || 'TechCorp'}</div>
                </div>
                <span style={{ fontSize: '0.75rem', padding: '0.2rem 0.5rem', borderRadius: '12px', background: 'rgba(16, 185, 129, 0.2)', color: 'var(--secondary)', fontWeight: 600 }}>
                  {iv.status?.toUpperCase() || 'SCHEDULED'}
                </span>
              </div>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.4rem', fontSize: '0.85rem' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  <User size={15} color="var(--primary)" />
                  <span>Student: <strong>{iv.student_name || 'Candidate'}</strong></span>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  <Calendar size={15} color="var(--text-secondary)" />
                  <span>{new Date(iv.scheduled_at).toLocaleString()}</span>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  <Clock size={15} color="var(--text-secondary)" />
                  <span>Duration: {iv.duration_minutes || 45} mins</span>
                </div>
              </div>

              {iv.location_or_link && (
                <div style={{ marginTop: 'auto', paddingTop: '0.75rem', borderTop: '1px solid var(--surface-border)' }}>
                  <a 
                    href={iv.location_or_link} 
                    target="_blank" 
                    rel="noopener noreferrer" 
                    className="btn btn-outline"
                    style={{ width: '100%', justifyContent: 'center', fontSize: '0.8rem', borderColor: 'var(--secondary)', color: 'var(--secondary)' }}
                  >
                    <Video size={14} /> Audit / Join Room <ExternalLink size={12} />
                  </a>
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
